default_lang: zh

menu:
  home: /
  archive: /archives
  categories: /categories
  tags: /tags
  about: /about
  github: https://github.com/cytrogen
  friends: /friends
  rss: /atom.xml

nav:
  pages:
    - home
    - archive
    - categories
    - tags
    - about
  
  external:
    - github
    - rss
  
  utility:
    - friends
    - languages
    - search

favicon: favicon.png
logo: favicon.png

# Disqus Comment
# disqus:

# Google Analytics
# ga: G-

# Copyright Infomation
startyear:

# Image Credits
enable_image_credit: false

# Blogroll / Friend Links
# friend_links:
#     - name:
#       url:
#       description:
#       lang:

# FontAwesome
# fas:

# hexo-generator-feed
rss: /atom.xml
