menu:
    博客: /
    关于: /about/
    归档: /archives/
    标签: /tags/
    GitHub: https://github.com/cytrogen
    RSS: /atom.xml

favicon: favicon.png
logo: favicon.png

# Comment
#disqus: cytrogen

# Google Analytics
#ga:

# Copyright Infomation
startyear: 2024

# Image Credits
enable_image_credit: false

# Friend Links
#friend_links:

# FontAwesome
#fas:

# hexo-renderer-markdown-it-plus
math:
    every_page: false
    mathjax:
        enable: true
        tags: none
    katex:
        enable: false
        copy_tex: false

# hexo-generator-feed
rss: /atom.xml
